
server:
  port: 8083


security:
  oauth2:
    resource:
      token-info-uri: http://localhost:8082/oauth/check_token
      jwt:

        key-alias: oauth2
        key-uri: http://localhost:8082/oauth/token_key
      id: ["oauth2"]
    client:
      client-id: oauth2
      client-secret: oauth2
      access-token-uri: ${auth-server}/oauth/token


spring:

  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:postgresql://zengshen.org/postgres?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true
    username: test
    password: 123456

#  redis:
#    host: 192.168.17.140
#    port: 6379
#    password: 123456
#    timeout: 10000ms
#    database: 0
#    lettuce:
#      pool:
#        # 连接池最大连接数（使用负值表示没有限制） 默认 8
#        max-active: 8
#        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
#        max-wait: -1ms
#        # 连接池中的最大空闲连接 默认 8
#        max-idle: 8
#        # 连接池中的最小空闲连接 默认 0
#        min-idle: 0
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

pagehelper:
  # 分页合理化参数配置
  reasonable: true
  # 支持通过 Mapper 接口参数来传递分页参数
  support-methods-arguments: true

logging:
  level:
    org.springframework.security: debug


# MinIO 配置
minio:
  endpoint: http://zengshen.org:9000      # MinIO服务地址
  bucketName: mycourse                      # 存储桶bucket名称
  accessKey: root                         # 用户名
  secretKey: 12345678                     # 密码

